### ISSUE TITLE
Bad result in garage floor.

### ISSUE THREAD

**Issue by Xiaxia1997** [PRBonn/SHINE_mapping#11]
I was trying to reconstruct the 20m*20m underground garage, but got a terrible floor. 
Here is the mesh and map,  we already had the lidar points around the floor, but got little mesh  around the floor.
![截图](https://user-images.githubusercontent.com/95740788/225258435-66de42ea-d33b-4383-8ae8-f947bc5b0414.PNG)
So what can I do to fix it?
**Another question** is about the rough mesh, in order to get mesh with higher resolution, which parameter should be adjusted? 
`mc_res_m` in marching cubes or `leaf_vox_size` ?

**Comment by StarryN** [comment]
Hello, We are not sure which problem it is based on your image, but the point cloud looks pretty noisy.
Could you provide us with your data? So we can test it and look for the problem.
For the second question. A smaller `leaf_vox_size` will make a finer sign distance field if your data is dense enough. And the `mc_res_m` is only for the mesh resolution extracted from this field. So the better choice is reducing them both.
