### ISSUE TITLE
Other dataset config file

### ISSUE THREAD

**Issue by zang09** [PRBonn/SHINE_mapping#13]
Hi, thank you for sharing your wonderful work!

Could you sharing the config files for other dataset? (e.g. Replica, IPB Office)

**Comment by YuePanEdward** [comment]
Thanks for your interest on our work.
You can use [the config files for indoor RGB-D datasets](https://github.com/PRBonn/SHINE_mapping/blob/master/config/rgbd/rgbd_batch.yaml) for Replica and IPB Office datasets.
