### ISSUE TITLE
If need to know the pose of each frame in advance during real-time operation?

### ISSUE THREAD

**Issue by Liansheng-Wang** [PRBonn/SHINE_mapping#14]
I thought this project could be run online and in real-time. 
I need to confirm with the author whether this work can be run without knowing the pose of each laser point cloud frame?
Looking forward to your reply very much.

**Comment by StarryN** [comment]
Hello Liangsheng.
Yes, In the incremental mapping mode, knowing all frames' poses in advance is unnecessary. We only need to know the poses of the previous and current frames.
