### ISSUE TITLE
Just  point cloud, no LiDAR point, Can a map be made?

### ISSUE THREAD

**Issue by AIBUWAN** [PRBonn/SHINE_mapping#16]
Hi, amazing work.

If I have some outdoor point cloud that from NeRF, not LiDAR point, can I map?

**Comment by AIBUWAN** [comment]
@marrblue Thanks. What about also adding the camera's internal and external information to build a map?

**Comment by YuePanEdward** [comment]
I think it's possible but not the main application for SHINE-Mapping. You may try to project the points generated from Nerf to the image frame and regard them as RGB-D images. In this case, using the `ray_loss: True` combined with `main_loss_type: dr` or `main_loss_type: dr_neus` may lead to better results.
