### ISSUE TITLE
MapVisualizer is always stucked when visualizing the incremental mapping process?

### ISSUE THREAD

**Issue by DeepDuke** [PRBonn/SHINE_mapping#17]
Hi, I was curious about your PC configuration to run the incremental mode? The MapVisualizer was very easy to be stucked during the incremental mode on my PC. My PC is with i7-12700F CPU and 3090Ti GPU.

**Comment by YuePanEdward** [comment]
Thanks for your interest in our work. 
Indeed, the MapVisualizer is not optimized. The interaction can only be made when the computation for each frame finishes. It's better to press [space] to pause and then drag to switch the viewpoint or zoom in and out.
