### ISSUE TITLE
bad result for maicity with voxel size 20cm

### ISSUE THREAD

**Issue by JunyuanDeng** [PRBonn/SHINE_mapping#2]
Thanks for your excellent work!

But when I test the mappings for maicity with voxel size 20 cm, the result turns to like below: 

![image](https://user-images.githubusercontent.com/62542727/208024908-09cf4201-d37a-4923-89ac-0b5a35deafc4.png)

It seems there are many holes and the disappear of pavement.

I just simply change the hyperparameter `leaf_vox_size` to 0.2 in `maicity_incre_reg.yaml` . How should I modify it to get a good result?

**Comment by YuePanEdward** [comment]
Thanks for your interest in our work.
The issue may be caused by the synthetic dataset and the marching cubes library we used.
You may set the `mc_res_m: 0.1` and you are expected to get a better result without the holes.

**Comment by Rotatingpencil** [comment]
Thanks for your reply, I will test it later!

**Comment by Rotatingpencil** [comment]
I have tried with `mc_res_m: 0.1`, it has no stranges holes anymore, but the result seems to be less good...
![微信截图_20230114005830](https://user-images.githubusercontent.com/62542727/212376816-cf9b4bfd-84ee-43c1-ba64-0f72400f2bd4.png)

**Comment by aartykov** [comment]
I could not reproduce the results in table 2 with the MaiCit dataset too. What should I do to get similar results as the ones mentioned on the paper? Thanks in advance.

**Comment by YuePanEdward** [comment]
> I could not reproduce the results in table 2 with the MaiCit dataset too. What should I do to get similar results as the ones mentioned on the paper? Thanks in advance.

Thanks for your interest in our work. You may check a similar issue here https://github.com/PRBonn/SHINE_mapping/issues/3#issuecomment-1367416983.
