### ISSUE TITLE
Noise results testing on the nuScenes dataset 

### ISSUE THREAD

**Issue by dachengxiaocheng** [PRBonn/SHINE_mapping#26]
Hey, thanks for releasing the amazing work! 

The method works very well on the KITTI dataset with 64-line lidar. I made a test on the nuScenes dataset with 32-line lidar. I get a very noisy result including a lot of holes on the ground. The 3D point on nuScenes dataset is more sparse than that of the KITTI dataset.

In order to fill the holes in the 3D surface, I use mc_res_m=0.1, and only sample the points on the "close-to-surface uniform sampling".

Any idea to make it works on the nuScenes dataset? Thank you so much.

**Comment by YuePanEdward** [comment]
Thanks for your interest in our work.
For sparse datasets such as nuScenes, to have higher completeness, it's better to set `tree_level_feat` larger (for example = 3) and set `mc_vis_level` larger (for example = 2). In this case, please also turn off `mc_with_octree`.

Here's the result I achieved on Nuscenes 0001 using the `kitti_batch.yaml` with the modifications mentioned above after 10k iterations.

![Screenshot from 2023-08-05 12-34-30](https://github.com/PRBonn/SHINE_mapping/assets/34207278/11cefe93-2c2f-46ba-92af-dbddeec7c392)


It would be great if you can tell me the sequence number corresponding to the image you posted so that we can also test it.

**Comment by dachengxiaocheng** [comment]
Hey, thanks so much for replying very soon!

I test it using the hyperparameter as you suggested. It seems there are no too many differences. 

I made a quick test on scene-0061 on the nuScenes-mini dataset. Could you have a quick test on this scene? 

Thank you.

**Comment by YuePanEdward** [comment]
![Screenshot from 2023-08-06 13-06-55](https://github.com/PRBonn/SHINE_mapping/assets/34207278/5f2e93e2-9d3d-47f4-bc15-5a79bf950573)
Hi, here's the result I got on 0061 with all the 382 LiDAR frames and the parameters mentioned above (after 10k iterations).
I've also tried to use only 38 frames (1 from every 10 frames) for the mapping, the results are shown below (still seem to be okayish but already with some holes):
![Screenshot from 2023-08-06 13-20-37](https://github.com/PRBonn/SHINE_mapping/assets/34207278/1d07828a-f36c-4702-824c-e718aa8b50aa)

But if you are using even fewer frames, then it could be too sparse for the mapping.

**Comment by dachengxiaocheng** [comment]
Thanks for sharing the results on Scene-0061.  It looks like your result is denser and has fewer holes in the ground.

I use the new code in your GitHub, and run the script "shine_batch.py" with "kitti_batch.yaml". 
I set the tree_level_feat=3, mc_vis_level=2 and mc_with_octree=False. 
I only modify the lidar_dataset.py to make it can load the nuScenes dataset. 
Besides these, nothing is changed. However, the result looks very sparser.  Is there anything I don't run the code in the right way? 

Could you help me to find out where is the problem? I can share my code with you. Thank you so much!

Here is my result after 10000 iterations. 

![snapshot00](https://github.com/PRBonn/SHINE_mapping/assets/9382330/dcc5a86e-b643-40d7-81f3-3bfaff6e4ac6)

**Comment by YuePanEdward** [comment]
I forgot to mention that I use `mc_res_m: 0.2` for a faster mesh reconstruction. But this would not make much difference in my opinion. There's no other modification from the latest code.
SHINE Mapping will also output a downsampled merged point cloud in the `map` folder under the results path. Is it possible for you to take a screenshot of the merged point cloud in some visualizer? Besides, I wonder how many frames of the point cloud you are using.

**Comment by dachengxiaocheng** [comment]
Hey, I use the point cloud from "sample_data" of nuScenes-mini dataset. For Scene-0061, there are 39 frames of lidar points and I use all of them. Here is the merged point cloud: 

![PC00](https://github.com/PRBonn/SHINE_mapping/assets/9382330/9e910018-35c3-4919-a871-dca741320713)

**Comment by dachengxiaocheng** [comment]
Hello, thanks for your help.

I find a bug in my data loading. Now I could get the denser reconstruction results similar to what you provided.
