### ISSUE TITLE
some question about the metric accuracy?

### ISSUE THREAD

**Issue by Zhangjyhhh** [PRBonn/SHINE_mapping#28]
Hi, thanks for your excellent work?
I run the evaluator.py on maicity dataset . I get the similar result as your result,except accuracy. my accuracy is 3.3 that corresponds to "MAE_accuracy". I'm not sure that is  "MAE_accuracy"  correspond to the accuracy?

**Comment by ljjTYJR** [comment]
I guess the issue comes from the selection of ground truth.
Refer to https://github.com/PRBonn/SHINE_mapping/issues/3#issuecomment-1367416983, which uses "Interaction point cloud" when evaluating accuracy

**Comment by ljjTYJR** [comment]
But I have a question that I used the provided configure file, I can not reproduce the same result as perfect as the result in https://github.com/PRBonn/SHINE_mapping/issues/3#issuecomment-1367416983

**Comment by Zhangjyhhh** [comment]
I use the "gt_map_pc_mai_inter_croped.ply" as ground truth, except "MAE_accuracy",other metric is better than the paper's metric.maybe you can use the /config/configicra2023  @ljjTYJR . 
so the MAE_accuracy is the accuracy ?

**Comment by ljjTYJR** [comment]
This is the reconstruction in https://github.com/PRBonn/SHINE_mapping/issues/3#issuecomment-1367416983
![Screenshot from 2023-09-06 21-50-44](https://github.com/PRBonn/SHINE_mapping/assets/35888427/5aaa0684-f34b-4639-878e-e0d463c3fae3)

This is the reconstruction I use the https://github.com/PRBonn/SHINE_mapping/blob/master/config/config_icra2023/maicity_batch.yaml
![Screenshot from 2023-09-06 21-51-24](https://github.com/PRBonn/SHINE_mapping/assets/35888427/34cc50b6-aa83-49e8-899f-6f83535c57a6)
In fact, I think the reconstruction with the above configuration file is already good. But I wonder how can I get the first one? It is really nice!

**Comment by Zhangjyhhh** [comment]
I have no idea， maybe you can ask the author, I wish you can figure out
