### ISSUE TITLE
how to train the freezed decoder (pre-trained) on a new dataset?

### ISSUE THREAD

**Issue by poodarchu** [PRBonn/SHINE_mapping#29]
How the pretrained model is obtained?
for a new dataset rather than thoses mentioned in the paper, how to get a pretrined decoder to make increcemental mapping work well?

**Comment by StarryN** [comment]
Hello @poodarchu , In our method, the decoder doesn't play a critical role. You may check #19 for the demo of training the map with a frozen MLP after initialization. For a new dataset, you can just use the replay method to train the map and decoder jointly with the first few (like 20 or 30) frames and then freeze the decoder. 

It is implemented in our replay version of increment mapping, and you can find a parameter in the config file:
https://github.com/PRBonn/SHINE_mapping/blob/73eaad60f5c60b90b5f9a5845482fccb5043fa1a/config/kitti/kitti_incre_replay.yaml#L38
