### ISSUE TITLE
How did you refine the pose of the Newer College Dataset? 

### ISSUE THREAD

**Issue by DeepDuke** [PRBonn/SHINE_mapping#30]
```
-- poses.txt: the refined pose of the sensor for the 1300 frames under the ground truth point cloud's reference coordinate system
```
![image](https://github.com/PRBonn/SHINE_mapping/assets/15854511/440333bc-0934-43bb-8d63-26d9529ccd2b)
 Hi, what method did you use to refine the poses for the Newer College  Dataset? And what's the difference between `poses.txt` and `poses_original.txt`  ?  TKS!

**Comment by YuePanEdward** [comment]
Thanks for the interest in our work. 
The poses are refined by registering the scan to `ncd_quad_gt_pc.ply` and taking the poses in `poses_original.txt` as the initial guess. We use open3d's point2plane ICP with a robust kernel for the registration. The difference between `poses.txt` and `poses_original.txt` is smaller than 10cm on average.

**Comment by DeepDuke** [comment]
Thank you!
