### ISSUE TITLE
The boosting time consumption of incremental shine-mapping on seq00 from MaiCity with 700 > pc_count_gpu_limit

### ISSUE THREAD

**Issue by laliwang** [PRBonn/SHINE_mapping#31]
Thanks for your great work in the implicit mapping of large-scale outdoor scenes! When I test your scripts `python shine_incre.py ./config/maicity/maicity_incre_replay.yaml` on the whole Maicity seq00 sequence, I notice that the time consumption of mapping(without marching_cubes and visualization) greatly boost when I set the `every_frame=1` in the configs, which is supposed to be 16s/it on the **CPU**. 
 Since the incremantal mapping only process frames of limited sliding windows, what is the necessity of restricting `pc_count_gpu_limit=500` in your implemention? And is it possible to lift this restriction for more practical and efficient incremental mapping on **GPU**?

**Comment by YuePanEdward** [comment]
Thanks for your interest in our project. 
It's a good catch. Indeed this `pc_count_gpu_limit` is not needed for the incremental mapping with sliding windows.
You can remove this limit for replaying-based incremental mapping mode.
