### ISSUE TITLE
How to compute the signed reconstruction error?

### ISSUE THREAD

**Issue by DeepDuke** [PRBonn/SHINE_mapping#32]
<img width="1329" alt="image" src="https://github.com/PRBonn/SHINE_mapping/assets/15854511/ad04614f-ebc3-43ce-90fc-9afaba9744df">
Hi, how did u compute the signed reconstruction error? I thought the error should be a non-negative value... How did u define the sign? TKS!

**Comment by StarryN** [comment]
Hello @DeepDuke, we used the cloud-mesh distance function in CloudCompare to generate this figure. The sign is determined automatically by the software.

![cloudcompare](https://github.com/PRBonn/SHINE_mapping/assets/8968747/d90bb766-ec2f-4a87-bb7d-aa06b8e818bf)

**Comment by DeepDuke** [comment]
Got it. Thank you!
