### ISSUE TITLE
Problem when trying to run the script

### ISSUE THREAD

**Issue by HamzaOuajhain** [PRBonn/SHINE_mapping#33]
Hello, 

I am trying to run your project, I have an Ubuntu 22.04 with cuda V11.8

nvcc --version returns V11.8.89

nvidia-smi Driver Version: 545.23.08    CUDA Version: 12.3

managed to installed the required dependencies
print(torch.__version__) return 1.12.1+cu116

when I try to run any command I get 

python shine_batch.py ./config/maicity/maicity_batch.yaml
Start ./experiments/maicity_batch_2024-01-13_20-59-06
Traceback (most recent call last):
  File "shine_batch.py", line 270, in <module>
    run_shine_mapping_batch()
  File "shine_batch.py", line 58, in run_shine_mapping_batch
    dataset = LiDARDataset(config, octree)
  File "/home/aspegique/Desktop/SHINE_mapping/dataset/lidar_dataset.py", line 34, in __init__
    self.calib = read_calib_file(config.calib_path)
  File "/home/aspegique/Desktop/SHINE_mapping/utils/pose.py", line 13, in read_calib_file
    calib_file = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xxx/data/mai_city/ply/sequences/01/calib.txt'

to download data I ran :
sh ./scripts/download_maicity.sh

Can anyone guide me to solve this problem

**Comment by HamzaOuajhain** [comment]
My appologies for my ignorance. I managed to change the paths inside the the _batch.yaml files and get it to work.

  pc_path: "./data/mai_city/ply/sequences/01/velodyne"
  pose_path: "./data/mai_city/ply/sequences/01/poses.txt"
  calib_path: "./data/mai_city/ply/sequences/01/calib.txt"

I will take this chance to ask a question regarding running of the program most of the time the visualiser crashes

![Screenshot from 2024-01-14 01-57-13](https://github.com/PRBonn/SHINE_mapping/assets/121122945/a37f3ae5-d59a-45e5-8bc9-7e5e78fcd228)

when running python shine_incre.py ./config/maicity/maicity_incre_replay.yaml

is this caused by my graphic card or cpu, my cpu is 100%

any help would be appreciated

**Comment by StarryN** [comment]
Hello, @HamzaOuajhain. Thanks for your interest.
The warning message you showed means that the open3d visualizer is waiting too long for the next update. You may just click "wait" and wait for the completion of the next processing loop.

**Comment by HamzaOuajhain** [comment]
@StarryN Got it, Thank you

**Comment by HamzaOuajhain** [comment]
@StarryN  Got it, Thank you.
