### ISSUE TITLE
octree issue

### ISSUE THREAD

**Issue by whwh747** [PRBonn/SHINE_mapping#35]
Thank you for your excellent work. In an octree, does each node correspond to a voxel with voxel embeddings on all eight vertices, and is multiresolution achieved by connecting the embeddings of leaf nodes and their ancestor nodes?

**Comment by StarryN** [comment]
Hello @whwh747. 
Yes, you are right. We sum up the interpolated features from different voxel levels to fuse the multiresolution information. This is implemented by maintaining one hash table in each voxel level rather than searching in a tree structure.

**Comment by whwh747** [comment]
i got it，thank you！
